name: chess-rag-env
channels:
  - conda-forge
  - defaults
dependencies:
  - aiohappyeyeballs=2.4.3
  - aiohttp=3.10.5
  - aiosignal=1.3.1
  - annotated-types=0.7.0
  - anyio=4.6.2.post1
  - async-timeout=4.0.3
  - attrs=24.2.0
  - blas=2.125
  - blas-devel=3.9.0
  - blinker=1.6.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.9.24
  - cachetools=5.3.3
  - certifi=2024.8.30
  - cffi=1.17.1
  - charset-normalizer=3.4.0
  - click=8.1.7
  - cloud-sql-python-connector=1.11.0
  - cryptography=43.0.3
  - dataclasses-json=0.6.7
  - exceptiongroup=1.2.2
  - expat=2.6.3
  - faiss=1.8.0
  - faiss-cpu=1.8.0
  - flask=3.0.3
  - frozenlist=1.5.0
  - google-api-core=2.19.1
  - google-api-python-client=2.154.0
  - google-auth=2.29.0
  - google-auth-httplib2=0.2.0
  - googleapis-common-protos=1.63.2
  - greenlet=3.0.1
  - h11=0.14.0
  - h2=4.1.0
  - hpack=4.0.0
  - httpcore=1.0.7
  - httplib2=0.22.0
  - httpx=0.27.2
  - httpx-sse=0.4.0
  - hyperframe=6.0.1
  - idna=3.10
  - itsdangerous=2.2.0
  - jinja2=3.1.4
  - jsonpatch=1.33
  - jsonpointer=2.0
  - langchain=0.3.8
  - langchain-community=0.3.8
  - langchain-core=0.3.21
  - langchain-text-splitters=0.3.2
  - langgraph=0.2.53
  - langgraph-checkpoint=2.0.5
  - langgraph-sdk=0.1.36
  - langsmith=0.1.145
  - libabseil=20240116.2
  - libblas=3.9.0
  - libcblas=3.9.0
  - libexpat=2.6.3
  - libfaiss=1.8.0
  - libffi=3.4.4
  - libgfortran5=14.2.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libopenblas=0.3.28
  - libprotobuf=4.25.3
  - libsqlite=3.46.0
  - libzlib=1.2.13
  - llvm-openmp=19.1.4
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - marshmallow=3.23.1
  - msgpack-python=1.1.0
  - multidict=6.1.0
  - mypy_extensions=1.0.0
  - ncurses=6.4
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openblas=0.3.28
  - openssl=3.4.0
  - orjson=3.10.7
  - packaging=24.2
  - pip=24.2
  - proto-plus=1.24.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.22
  - pydantic=2.8.2
  - pydantic-core=2.20.1
  - pydantic-settings=2.6.1
  - pymysql=1.0.2
  - pyopenssl=24.2.1
  - pyparsing=3.2.0
  - pysocks=1.7.1
  - python=3.12.2
  - python-dotenv=1.0.1
  - python_abi=3.12
  - pyyaml=6.0.2
  - readline=8.2
  - requests=2.32.3
  - requests-toolbelt=1.0.0
  - rsa=4.7.2
  - setuptools=75.1.0
  - sniffio=1.3.1
  - sqlalchemy=2.0.34
  - sqlite=3.45.3
  - tenacity=8.5.0
  - tk=8.6.14
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - typing_inspect=0.9.0
  - tzdata=2024b
  - uritemplate=4.1.1
  - urllib3=2.2.3
  - werkzeug=3.0.6
  - wheel=0.44.0
  - xz=5.4.6
  - yaml=0.2.5
  - yarl=1.11.0
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - docstring-parser==0.16
      - google-cloud-aiplatform==1.73.0
      - google-cloud-bigquery==3.27.0
      - google-cloud-core==2.4.1
      - google-cloud-resource-manager==1.13.1
      - google-cloud-storage==2.18.2
      - google-crc32c==1.6.0
      - google-resumable-media==2.7.2
      - grpc-google-iam-v1==0.13.1
      - grpcio==1.68.0
      - grpcio-status==1.68.0
      - langchain-google-vertexai==2.0.7
      - protobuf==5.28.3
      - python-dateutil==2.9.0.post0
      - shapely==2.0.6
      - six==1.16.0