name: chessbot-hf
channels:
  - conda-forge
  - defaults
dependencies:
  - accelerate=1.3.0
  - aiohappyeyeballs=2.4.4
  - aiohttp=3.11.10
  - aiosignal=1.2.0
  - annotated-types=0.6.0
  - anyio=4.6.2
  - attrs=24.3.0
  - blas=1.0
  - blinker=1.9.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2024.12.31
  - certifi=2024.12.14
  - charset-normalizer=3.3.2
  - click=8.1.7
  - dataclasses-json=0.6.5
  - datasets=2.19.1
  - deprecated=1.2.13
  - dill=0.3.8
  - faiss=1.9.0
  - faiss-cpu=1.9.0
  - filelock=3.13.1
  - flask=3.1.0
  - freetype=2.12.1
  - frozenlist=1.5.0
  - fsspec=2024.3.1
  - gflags=2.2.2
  - glog=0.7.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - greenlet=3.1.1
  - h11=0.14.0
  - httpcore=1.0.2
  - httpx=0.27.0
  - httpx-sse=0.4.0
  - huggingface_hub=0.24.6
  - idna=3.7
  - importlib-metadata=7.0.1
  - itsdangerous=2.2.0
  - jinja2=3.1.4
  - joblib=1.4.2
  - jsonpatch=1.33
  - jsonpointer=2.1
  - krb5=1.21.3
  - langchain=0.3.12
  - langchain-community=0.3.12
  - langchain-core=0.3.25
  - langchain-huggingface=0.1.2
  - langchain-text-splitters=0.3.3
  - langgraph=0.2.66
  - langgraph-checkpoint=2.0.10
  - langgraph-sdk=0.1.51
  - langsmith=0.1.147
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20240116.2
  - libarrow=17.0.0
  - libarrow-acero=17.0.0
  - libarrow-dataset=17.0.0
  - libarrow-substrait=17.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.11.1
  - libcxx=19.1.7
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.4
  - libfaiss=1.9.0
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libgoogle-cloud=2.29.0
  - libgoogle-cloud-storage=2.29.0
  - libgrpc=1.62.2
  - libiconv=1.17
  - libjpeg-turbo=3.0.3
  - liblapack=3.9.0
  - libnghttp2=1.64.0
  - libopenblas=0.3.21
  - libopentelemetry-cpp=1.16.1
  - libopentelemetry-cpp-headers=1.16.1
  - libparquet=17.0.0
  - libpng=1.6.45
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - libsqlite=3.45.2
  - libssh2=1.11.1
  - libthrift=0.20.0
  - libtiff=4.7.0
  - libtorch=2.5.1
  - libutf8proc=2.8.0
  - libuv=1.50.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxml2=2.13.5
  - libzlib=1.3.1
  - llvm-openmp=19.1.7
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - marshmallow=3.19.0
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - msgpack-python=1.1.0
  - multidict=6.1.0
  - multiprocess=0.70.15
  - mypy_extensions=1.0.0
  - ncurses=6.4
  - networkx=3.4.2
  - nlohmann_json=3.11.2
  - nomkl=3.0
  - numexpr=2.10.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.5.3
  - openssl=3.4.0
  - opentelemetry-api=1.26.0
  - orc=2.0.2
  - orjson=3.10.14
  - packaging=24.2
  - pandas=2.2.3
  - pillow=11.1.0
  - pip=24.2
  - prometheus-cpp=1.2.4
  - propcache=0.2.0
  - protobuf=4.25.3
  - psutil=6.1.1
  - pthread-stubs=0.3
  - pyarrow=17.0.0
  - pyarrow-core=17.0.0
  - pydantic=2.10.3
  - pydantic-core=2.27.1
  - pydantic-settings=2.6.1
  - pysocks=1.7.1
  - python=3.11.8
  - python-dateutil=2.9.0post0
  - python-dotenv=0.21.0
  - python-tzdata=2023.3
  - python-xxhash=3.5.0
  - python_abi=3.11
  - pytorch=2.5.1
  - pytz=2024.1
  - pyyaml=6.0.2
  - re2=2023.09.01
  - readline=8.2
  - regex=2024.11.6
  - requests=2.32.3
  - requests-toolbelt=1.0.0
  - safetensors=0.4.5
  - scikit-learn=1.5.2
  - scipy=1.15.1
  - sentence-transformers=3.3.1
  - setuptools=75.1.0
  - six=1.16.0
  - sleef=3.7
  - snappy=1.2.1
  - sniffio=1.3.0
  - sqlalchemy=2.0.37
  - sqlite=3.45.2
  - sympy=1.13.3
  - tenacity=9.0.0
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - tokenizers=0.20.1
  - tqdm=4.66.5
  - transformers=4.45.2
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_inspect=0.9.0
  - tzdata=2025a
  - urllib3=2.3.0
  - werkzeug=3.1.3
  - wheel=0.44.0
  - wrapt=1.17.0
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xxhash=0.8.0
  - xz=5.4.6
  - yaml=0.2.5
  - yarl=1.18.0
  - zipp=3.21.0
  - zlib=1.3.1
  - zstd=1.5.6