name: chessbot
channels:
  - conda-forge
  - defaults
dependencies:
  - aiohappyeyeballs=2.4.4
  - aiohttp=3.11.10
  - aiosignal=1.2.0
  - annotated-types=0.6.0
  - anyio=4.6.2
  - async-timeout=4.0.3
  - attrs=24.3.0
  - blas=1.0=openblas
  - blinker=1.6.2
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.12.31
  - certifi=2024.12.14
  - charset-normalizer=3.3.2
  - click=8.1.7
  - dataclasses-json=0.6.7
  - faiss=1.9.0
  - faiss-cpu=1.9.0
  - flask=3.0.3
  - frozenlist=1.5.0
  - greenlet=3.1.1
  - h11=0.14.0
  - httpcore=1.0.2
  - httpx-sse=0.4.0
  - idna=3.7
  - itsdangerous=2.2.0
  - jinja2=3.1.4
  - jsonpatch=1.33
  - jsonpointer=2.1
  - langchain=0.3.14
  - langchain-community=0.3.14
  - langchain-core=0.3.30
  - langchain-text-splitters=0.3.3
  - langgraph=0.2.64
  - langgraph-checkpoint=2.0.10
  - langgraph-sdk=0.1.51
  - langsmith=0.1.147
  - libexpat=2.6.4
  - libfaiss=1.9.0
  - libffi=3.4.4
  - libgfortran5=11.3.0
  - libopenblas=0.3.21
  - libsqlite=3.45.2
  - libzlib=1.3.1
  - llvm-openmp=14.0.6
  - markupsafe=2.1.3
  - marshmallow=3.25.1
  - msgpack-python=1.1.0
  - multidict=6.1.0
  - mypy_extensions=1.0.0
  - ncurses=6.4
  - numexpr=2.10.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openssl=3.4.0
  - orjson=3.10.14
  - packaging=24.2
  - pandas=2.2.3
  - pip=24.2
  - propcache=0.2.0
  - pydantic-settings=2.7.1
  - pysocks=1.7.1
  - python=3.11.8
  - python-dateutil=2.9.0post0
  - python-dotenv=1.0.1
  - python-tzdata=2023.3
  - python_abi=3.11
  - pytz=2024.1
  - pyyaml=6.0.2
  - readline=8.2
  - requests=2.32.3
  - requests-toolbelt=1.0.0
  - setuptools=75.1.0
  - six=1.16.0
  - sniffio=1.3.0
  - sqlalchemy=2.0.37
  - sqlite=3.45.2
  - tenacity=9.0.0
  - tk=8.6.13
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_inspect=0.9.0
  - tzdata=2024b
  - urllib3=2.3.0
  - werkzeug=3.0.6
  - wheel=0.44.0
  - xz=5.4.6
  - yaml=0.2.5
  - yarl=1.18.0
  - zlib=1.3.1
  - pip:
      - cachetools==5.5.0
      - docstring-parser==0.16
      - google-api-core==2.24.0
      - google-auth==2.37.0
      - google-cloud-aiplatform==1.77.0
      - google-cloud-bigquery==3.27.0
      - google-cloud-core==2.4.1
      - google-cloud-resource-manager==1.14.0
      - google-cloud-storage==2.19.0
      - google-crc32c==1.6.0
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.66.0
      - grpc-google-iam-v1==0.14.0
      - grpcio==1.69.0
      - grpcio-status==1.69.0
      - httpx==0.28.1
      - langchain-google-vertexai==2.0.11
      - proto-plus==1.25.0
      - protobuf==5.29.3
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - rsa==4.9
      - shapely==2.0.6